name: my_portfolio
description: Deepanshu Chowdhary.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  smooth_scroll_web:
  flutter_screenutil: ^4.0.2+3
  intl_phone_field: ^1.3.0
  url_launcher:
  transparent_image:
  carousel_slider: ^3.0.0
  google_fonts:
  animated_text_kit:
  animations:
  percent_indicator:

  animate_do: ^1.7.5
  bloc: ^6.1.1
  device_preview: ^0.5.5
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  simple_animations: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
